name: supmap

services:
  database:
    image: postgis/postgis:17-3.5
    environment:
      - POSTGRES_DB=supmap
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/SUPMAP.sql:/docker-entrypoint-initdb.d/SUPMAP.sql
    ports:
      - "5432:5432"
  
  api:
    build: ./api
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=supmap
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CRYPTO_KEY=${CRYPTO_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:80/
      - GRAPHHOPPER_API_KEY=${GRAPHHOPPER_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - database

  web:
    build: ./web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://api:8000/v1
    ports:
      - "80:3000"
    depends_on:
      - api

volumes:
  database_data: