name: supmap

services:
  api:
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
    command: sh -c "npm install && npm run dev"

  web:
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app
    command: sh -c "npm install && npm run dev"