name: supmap

services:
  database:
    image: postgis/postgis:17-3.5
    environment:
      - POSTGRES_DB=supmap
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  
  routing_engine:
    build: ./routing-engine
    volumes:
      - routing_engine_data:/data/valhalla

  api:
    build: ./api
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=supmap
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - CRYPTO_KEY=${CRYPTO_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:8000/auth/google/callback
      - DEFAULT_ROLE=user
      - ROUTING_ENGINE_URL=http://routing_engine:8002
    depends_on:
      - database
      - routing_engine

  web:
    build: ./web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - "80:3000"
    depends_on:
      - api

volumes:
  database_data:
  routing_engine_data: