CREATE TABLE "user" (
  -- Columns
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "email" TEXT,
  "name" TEXT,
  "password" TEXT,
  "picture" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT "user_primary_key_id" PRIMARY KEY ("id"),
  CONSTRAINT "user_unique_email" UNIQUE ("email"),
  CONSTRAINT "user_not_null_email" CHECK ("email" IS NOT NULL),
  CONSTRAINT "user_not_null_name" CHECK ("name" IS NOT NULL),
  CONSTRAINT "user_not_null_created_at" CHECK ("created_at" IS NOT NULL)
);

CREATE TABLE "role" (
  -- Columns
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT,
  "is_administrator" BOOLEAN DEFAULT FALSE,
  "can_manage_users" BOOLEAN DEFAULT FALSE,
  "can_manage_roles" BOOLEAN DEFAULT FALSE,
  "can_manage_alerts" BOOLEAN DEFAULT FALSE,

  -- Constraints
  CONSTRAINT "role_primary_key_id" PRIMARY KEY ("id"),
  CONSTRAINT "role_unique_name" UNIQUE ("name"),
  CONSTRAINT "role_not_null_name" CHECK ("name" IS NOT NULL),
  CONSTRAINT "role_not_null_is_administrator" CHECK ("is_administrator" IS NOT NULL),
  CONSTRAINT "role_not_null_can_manage_users" CHECK ("can_manage_users" IS NOT NULL),
  CONSTRAINT "role_not_null_can_manage_roles" CHECK ("can_manage_roles" IS NOT NULL),
  CONSTRAINT "role_not_null_can_manage_alerts" CHECK ("can_manage_alerts" IS NOT NULL)
);

CREATE TABLE "user_role" (
  -- Columns
  "user_id" BIGINT,
  "role_id" BIGINT,

  -- Constraints
  CONSTRAINT "user_role_primary_key_user_id_role_id" PRIMARY KEY ("user_id", "role_id"),
  CONSTRAINT "user_role_foreign_key_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "user_role_foreign_key_role_id" FOREIGN KEY ("role_id") REFERENCES "role" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "account" (
  -- Columns
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT,
  "provider" TEXT,
  "provider_account_id" TEXT,
  "access_token" TEXT,
  "refresh_token" TEXT,
  "expires_at" TIMESTAMPTZ,
  "scope" TEXT,

  -- Constraints
  CONSTRAINT "account_primary_key_id" PRIMARY KEY ("id"),
  CONSTRAINT "account_not_null_user_id" CHECK ("user_id" IS NOT NULL),
  CONSTRAINT "account_not_null_provider" CHECK ("provider" IS NOT NULL),
  CONSTRAINT "account_not_null_provider_account_id" CHECK ("provider_account_id" IS NOT NULL),
  CONSTRAINT "account_not_null_access_token" CHECK ("access_token" IS NOT NULL),
  CONSTRAINT "account_not_null_refresh_token" CHECK ("refresh_token" IS NOT NULL),
  CONSTRAINT "account_not_null_expires_at" CHECK ("expires_at" IS NOT NULL),
  CONSTRAINT "account_not_null_scope" CHECK ("scope" IS NOT NULL),
  CONSTRAINT "account_foreign_key_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "route" (
  -- Columns
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT,
  "start" GEOMETRY(Point, 4326),
  "end" GEOMETRY(Point, 4326),
  "route" GEOMETRY(LineString, 4326),
  "distance" DOUBLE PRECISION,
  "duration" DOUBLE PRECISION,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT "route_primary_key_id" PRIMARY KEY ("id"),
  CONSTRAINT "route_not_null_user_id" CHECK ("user_id" IS NOT NULL),
  CONSTRAINT "route_not_null_start" CHECK ("start" IS NOT NULL),
  CONSTRAINT "route_not_null_end" CHECK ("end" IS NOT NULL),
  CONSTRAINT "route_not_null_distance" CHECK ("distance" IS NOT NULL),
  CONSTRAINT "route_not_null_duration" CHECK ("duration" IS NOT NULL),
  CONSTRAINT "route_not_null_created_at" CHECK ("created_at" IS NOT NULL),
  CONSTRAINT "route_foreign_key_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "alert_type" (
  -- Columns
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT,
  "value" FLOAT,

  -- Constraints
  CONSTRAINT "alert_type_primary_key_id" PRIMARY KEY ("id"),
  CONSTRAINT "alert_type_unique_name" UNIQUE ("name"),
  CONSTRAINT "alert_type_not_null_name" CHECK ("name" IS NOT NULL),
  CONSTRAINT "alert_type_not_null_value" CHECK ("value" IS NOT NULL)
);

CREATE TABLE "alert" (
  -- Columns
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "alert_type_id" BIGINT,
  "user_id" BIGINT,
  "point" GEOMETRY(Point, 4326),
  "created_at" TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT "alert_primary_key_id" PRIMARY KEY ("id"),
  CONSTRAINT "alert_not_null_alert_type_id" CHECK ("alert_type_id" IS NOT NULL),
  CONSTRAINT "alert_not_null_user_id" CHECK ("user_id" IS NOT NULL),
  CONSTRAINT "alert_not_null_point" CHECK ("point" IS NOT NULL),
  CONSTRAINT "alert_not_null_created_at" CHECK ("created_at" IS NOT NULL),
  CONSTRAINT "alert_foreign_key_alert_type_id" FOREIGN KEY ("alert_type_id") REFERENCES "alert_type" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "alert_foreign_key_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "alert_vote" (
  -- Columns
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "alert_id" BIGINT,
  "user_id" BIGINT,
  "vote" BOOLEAN,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT "alert_vote_primary_key_id" PRIMARY KEY ("id"),
  CONSTRAINT "alert_vote_not_null_alert_id" CHECK ("alert_id" IS NOT NULL),
  CONSTRAINT "alert_vote_not_null_user_id" CHECK ("user_id" IS NOT NULL),
  CONSTRAINT "alert_vote_not_null_vote" CHECK ("vote" IS NOT NULL),
  CONSTRAINT "alert_vote_not_null_created_at" CHECK ("created_at" IS NOT NULL),
  CONSTRAINT "alert_vote_foreign_key_alert_id" FOREIGN KEY ("alert_id") REFERENCES "alert" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "alert_vote_foreign_key_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);