CREATE TABLE "user" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "email" text UNIQUE NOT NULL,
  "name" text NOT NULL,
  "password" text,
  "picture" text,
  "role" text NOT NULL DEFAULT 'user',
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "modified_on" timestamp NOT NULL DEFAULT (NOW())
);

CREATE TABLE "account" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "provider" text NOT NULL,
  "provider_account_id" text NOT NULL,
  "access_token" text NOT NULL,
  "refresh_token" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "scope" text NOT NULL
);

CREATE TABLE "route" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "graphhopper_response" json NOT NULL,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "created_by" bigint NOT NULL,
  "modified_on" timestamp NOT NULL DEFAULT (NOW()),
  "modified_by" bigint NOT NULL
);

CREATE TABLE "incident" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "type" text NOT NULL,
  "location" geometry(Point,4326) NOT NULL,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "created_by" bigint NOT NULL,
  "modified_on" timestamp NOT NULL DEFAULT (NOW()),
  "modified_by" bigint NOT NULL
);

CREATE TABLE "incident_vote" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "value" boolean NOT NULL,
  "incident_id" bigint NOT NULL,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "created_by" bigint NOT NULL,
  "modified_on" timestamp NOT NULL DEFAULT (NOW()),
  "modified_by" bigint NOT NULL
);

ALTER TABLE "account" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "route" ADD FOREIGN KEY ("created_by") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "route" ADD FOREIGN KEY ("modified_by") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "incident" ADD FOREIGN KEY ("created_by") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "incident" ADD FOREIGN KEY ("modified_by") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "incident_vote" ADD FOREIGN KEY ("created_by") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "incident_vote" ADD FOREIGN KEY ("modified_by") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "incident_vote" ADD FOREIGN KEY ("incident_id") REFERENCES "incident" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
